# Generated by Django 5.2.16 on 2026-08-06 04:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_avatar_url_profile_banner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default='defaults/banner.jpg', upload_to=accounts.models.banner_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/profile.png', upload_to=accounts.models.avatar_upload_path),
        ),
    ]
