# Generated by Django 5.2.16 on 2026-08-07 08:14

import django.db.models.deletion
import personas.models
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('topic_type', models.CharField(choices=[('broad', 'Broad'), ('narrow', 'Narrow')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=personas.models.avatar_upload_path)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=personas.models.banner_upload_path)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.persona')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.topic')),
            ],
            options={
                'unique_together': {('persona', 'topic')},
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='topics',
            field=models.ManyToManyField(related_name='personas', through='personas.PersonaTopic', to='personas.topic'),
        ),
    ]
