# Generated by Django 5.2.16 on 2026-08-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='persona_banners/'),
        ),
        migrations.AddField(
            model_name='persona',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
