# Generated by Django 5.2.16 on 2026-08-07 08:14

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contains_media', models.BooleanField(default=False)),
                ('likes_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('impressions_count', models.IntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('author_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=500)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.topic')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='posts', through='posts.PostTopic', to='personas.topic'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='personas.persona')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'indexes': [models.Index(fields=['post'], name='posts_comme_post_id_06cfd5_idx'), models.Index(fields=['parent_comment'], name='posts_comme_parent__49b217_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='posttopic',
            index=models.Index(fields=['post', 'topic'], name='posts_postt_post_id_7d12e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posttopic',
            unique_together={('post', 'topic')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author_persona'], name='posts_post_author__d138ae_idx'),
        ),
    ]
