# Generated by Django 5.2.16 on 2026-08-06 04:05

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to=posts.models.post_media_upload_path),
        ),
    ]
