# Generated by Django 5.2.16 on 2026-08-07 09:01

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmedia',
            name='media_url',
        ),
        migrations.AddField(
            model_name='postmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.post_media_upload_path),
        ),
    ]
