# Generated by Django 5.2.16 on 2026-08-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('posts', '0002_remove_postmedia_media_url_postmedia_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttopic',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='posttopic',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topics',
        ),
        migrations.AddField(
            model_name='post',
            name='broad_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broad_posts', to='personas.topic'),
        ),
        migrations.AddField(
            model_name='post',
            name='narrow_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='narrow_posts', to='personas.topic'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['broad_topic', '-created_at'], name='posts_post_broad_t_eee1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['narrow_topic', '-created_at'], name='posts_post_narrow__857730_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.DeleteModel(
            name='PostTopic',
        ),
    ]
