# Generated by Django 5.2.16 on 2026-08-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posttopic_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
    ]
