# Generated by Django 5.2.16 on 2026-08-07 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversationparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationParticipant',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
