# Generated by Django 6.0.7 on 2026-08-05 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.FloatField(default=0)),
                ('position', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='content_based', max_length=30)),
                ('served_at', models.DateTimeField(auto_now_add=True)),
                ('is_clicked', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='personas.persona')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='posts.post')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
